CREATE TABLE usuarios (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(15) NOT NULL,
    perfis VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
